#!/bin/bash
#Instalando Remmina no Ubuntu 16.04 LTS
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next -y
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard -y
